[project]
name = "odoo-addons-oca-l10n-japan"
version = "18.0.20251209.0"
dependencies = [
    "odoo-addon-account_move_delivery_invoice==18.0.*",
    "odoo-addon-account_payment_term_cutoff_day==18.0.*",
    "odoo-addon-account_tax_rounding_method==18.0.*",
    "odoo-addon-l10n_jp_address_layout==18.0.*",
    "odoo-addon-l10n_jp_country_state==18.0.*",
    "odoo-addon-l10n_jp_partner_title_qweb==18.0.*",
    "odoo-addon-l10n_jp_partner_zip_address==18.0.*",
    "odoo-addon-report_alternative_layout==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
